language: haskell
ghc: 7.6
install:
  - cabal install --flag '-watchserver -previewserver' hakyll
  - cabal install --dependencies-only
script:
  - cabal exec lunarsite build
  - cabal exec lunarsite check
