language: haskell
ghc: 7.6
env:
  global:
    - secure: "HlDP2le4lW8BDsVNt4M+PZ54kJrdI1KLrjk2qW2dtAoq0U3vo+iiR4K8W0c/xxqYhTlSCUc8CbkfGgsoEBRuHqBMgEGdUxsEvDiFHoCHPqe8qgC7sW6cNzVCjRvjo4e/MLRsIIppuUWjrz5wyCVOHCh4hgg8Jw3/Ba3Wutwb/9s="
install:
  - cabal install --flag '-watchserver -previewserver' hakyll
  - cabal install --dependencies-only
  # Required for syntax highlighting
  - pip install pygments
script:
  - cabal run lunarsite build
  - cabal run lunarsite check
after_success:
- bash travis-deploy.bash
